### PR TITLE
prevent running wakatime when entity is empty

### LINKED ISSUE #6: Issue in Terminal/Bash Integration
Can somebody here help me troubleshoot this problem?I just followed the guide at https://wakatime.com/help/plugins/terminal under Bash section but after doing all the guide, every time I open my bash, this error always appear:

> usage: wakatime [-h] [--entity FILE] [--key KEY] [--write] [--plugin PLUGIN]
>                 [--time time] [--lineno LINENO] [--cursorpos CURSORPOS]
>                 [--entity-type ENTITY_TYPE] [--proxy PROXY]
>                 [--project PROJECT] [--alternate-project ALTERNATE_PROJECT]
>                 [--alternate-language ALTERNATE_LANGUAGE]
>                 [--hostname HOSTNAME] [--disableoffline] [--hidefilenames]
>                 [--exclude EXCLUDE] [--include INCLUDE] [--extra-heartbeats]
>                 [--logfile LOGFILE] [--apiurl API_URL] [--timeout TIMEOUT]
>                 [--config CONFIG] [--verbose] [--version]
> wakatime: error: argument --entity is required

Wakatime works after 2 or more `clear` command. I guess there is something wrong with the bash-wakatime.sh. I did some chown and chmod 666 on .waka* files: `.wakatime.cfg` `.wakatime.db` and `.wakatime.log`, but still, the error still appears.

Thank you for your help! :)

### PR DESCRIPTION
**Pull request by alanhamlett**
To fix #6

### CODE REVIEW

**Comment by alanhamlett** [comment]
What do you mean by `will not leave whitespaces into the returning string`? Which string is the returning string?

I'm all for simplifying it, but I read the `-z` flag will treat whitespace as non-empty, so the regex is needed to remove whitespace before checking if empty.

**Comment by irondoge** [comment]
I mean in bash, `[ -z "$(echo $(printf "     \t  "))" ]` is always true because the `$()` notation epur the whitespaces when they are not escaped by double quotes.

Plus, the `[[` and the regex embed notation are not fully compliant with some old versions of bash.

**Comment by alanhamlett** [comment]
I tested the `-z` condition like:

```
entity=" "
if [[ ! -z "${entity// }" ]]; then
  echo "Entity is not empty"
else
  echo "Entity is empty"
fi
entity="foobar"
if [[ ! -z "${entity// }" ]]; then
  echo "Entity is not empty"
else
  echo "Entity is empty"
fi
```
Output:
```
Entity is empty
Entity is not empty
```

What's the best way to check if a variable is empty or whitespace in bash?

**Comment by irondoge** [comment]
This is the version I suggest:

```Bash
entity=" "
result=$(echo $entity)
if [ -n "$result" ]; then
  echo "Entity is not empty"
else
  echo "Entity is empty"
fi
entity="foobar"
result=$(echo $entity)
if [ -z "$result" ]; then
  echo "Entity is empty"
else
  echo "Entity is not empty"
fi
```

And this is how it can be applied to your pull request:
```Bash
version="0.1.1" # time to increment this
entity=$(echo $(fc -ln -0) | cut -d ' ' -f1)
[ -z "$entity" ] && return # $entity is not empty or only whitespace
(wakatime --write --plugin "bash-wakatime/$version" --entity-type app --project "$project" --entity "$entity" 2>&1 > /dev/null &)
```

**Pull request merged**
